---
title: "2. Feature Engineering"
output: html_notebook
---

```{r setup, include=FALSE}
load.libraries <- c('data.table', 'testthat', 'gridExtra', 'corrplot', 'GGally', 'ggplot2', 'e1071', 'dplyr','plyr', 'reticulate', 'e1071')
install.lib <- load.libraries[!load.libraries %in% installed.packages()]
for(libs in install.lib) install.packages(libs, dependences = TRUE)
sapply(load.libraries, require, character = TRUE)
use_python("~/anaconda3/envs/xtncpy/bin/python")
knitr::knit_engines$set(python = reticulate::eng_python)
```

### Loading up raw data per player and team performance

```{r}
players_raw <- fread('data_raw/core/People.csv')
teams_raw <- fread('data_raw/core/Teams.csv')
batting_raw  <- fread('data_raw/core/Teams.csv')
pitching_raw <- fread('data_raw/core/Pitching.csv')
fielding_raw  <- fread('data_raw/core/Fielding.csv')
```

we will train 2016 data to infer on 2017
```{r}
games <- fread('data/game_log/GL2016.csv')
```

```{r}
isHomeWin <- function(homescore, visitorscore){
  if (homescore > visitorscore){
    1
  }
  else {
    -1
  }
}

games$homeWin <- as.vector(mapply(isHomeWin, games$HomeScore, games$VisitorScore))
games$homeWin
```


```{r}
games %>% colnames()
```

```{r}
games_data <- games
to_be_dropped <- c("VisitorScore","HomeScore", "HomeLeague", "VisitorLeague", "DayNight", "Dates")

for (el in to_be_dropped){
  games_data[[el]] <- NULL
}

games_data %>% colnames()
games_data %>% head()
```




```{r}
games_data %>% dim()
```

```{r}

pitchers_feature <- c("G", "GD", "CG","SHO", "SV", "IPouts", "H", "ERA", "BB", "HBP")


pitchers_feature_home <- as.vector(sapply(pitchers_feature, function(feat){
  paste("HomeStartingPitcher", feat, sep = "_")
}))

pitchers_feature_visitor <- as.vector(sapply(pitchers_feature, function(feat){
  paste("VisitorStartingPitcher", feat, sep = "_")
}))
pitchers_feature_home
```


```{r}
games_data[,pitchers_feature_home] <- NA
games_data[,pitchers_feature_visitor] <- NA
games_data %>% colnames()
```


```{r}
updateId <- function(df, feature){
  newIDs <- c()
  for (rID in df[[feature]]){
    nID <- players_raw[[which(players_raw$retroID == rID),"playerID"]]
    newIDs <- c(newIDs, nID)
  }
  df[[feature]] <- newIDs
  df
}

```

```{r}
games_data <- updateId(games_data, "HomeStartingPitcher")
games_data <- updateId(games_data, "HomeStartingPlayer_1")
games_data <- updateId(games_data, "HomeStartingPlayer_2")
games_data <- updateId(games_data, "HomeStartingPlayer_3")
games_data <- updateId(games_data, "HomeStartingPlayer_4")
games_data <- updateId(games_data, "HomeStartingPlayer_5")
games_data <- updateId(games_data, "HomeStartingPlayer_6")
games_data <- updateId(games_data, "HomeStartingPlayer_7")
games_data <- updateId(games_data, "HomeStartingPlayer_8")
games_data <- updateId(games_data, "HomeStartingPlayer_9")
games_data <- updateId(games_data, "VisitorStartingPitcher")
games_data <- updateId(games_data, "VisitorStartingPlayer_1")
games_data <- updateId(games_data, "VisitorStartingPlayer_2")
games_data <- updateId(games_data, "VisitorStartingPlayer_3")
games_data <- updateId(games_data, "VisitorStartingPlayer_4")
games_data <- updateId(games_data, "VisitorStartingPlayer_5")
games_data <- updateId(games_data, "VisitorStartingPlayer_6")
games_data <- updateId(games_data, "VisitorStartingPlayer_7")
games_data <- updateId(games_data, "VisitorStartingPlayer_8")
games_data <- updateId(games_data, "VisitorStartingPlayer_9")

games_data
```


```{r}

computeFeature <- function(df, featureList, colBaseName) {
  
  for (feat in featureList) {
    colName <- paste(colBaseName, feat, sep = "_")  
    df[[colName]] <- as.vector(sapply(df[[colBaseName]], function(x){
      
    }))
  }
  df
}
```

